# Generated by Django 5.2.17 on 2026-09-17 02:28

import apps.events.tokens
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateTimeField()),
                ('cover_storage_key', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Activo'), ('FINISHED', 'Finalizado'), ('EXPIRED', 'Expirado'), ('PENDING_DELETE', 'Pendiente de eliminación'), ('DELETED', 'Eliminado')], default='DRAFT', max_length=24)),
                ('public_token', models.CharField(default=apps.events.tokens.generate_public_token, editable=False, max_length=64, unique=True)),
                ('public_access_enabled', models.BooleanField(default=True)),
                ('settings', models.JSONField(default=dict)),
                ('settings_version', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='operators.operator')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventtype')),
            ],
            options={
                'ordering': ('-event_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ReservedVideoToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_token', models.CharField(default=apps.events.tokens.generate_public_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible para asignar'), ('ASSIGNED', 'Asignado a una grabación'), ('READY', 'Video disponible'), ('EXPIRED', 'Expirado')], default='AVAILABLE', max_length=20)),
                ('assigned_video_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tokens', to='events.event')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['operator', 'status'], name='events_even_operato_fc01d5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['retention_until'], name='events_even_retenti_8ed7d0_idx'),
        ),
        migrations.AddIndex(
            model_name='reservedvideotoken',
            index=models.Index(fields=['event', 'status'], name='events_rese_event_i_870760_idx'),
        ),
    ]
