# Generated by Django 5.2.17 on 2026-09-17 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_seed_event_types'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_backend', models.CharField(default='local', max_length=30)),
                ('storage_key', models.CharField(blank=True, max_length=500)),
                ('thumbnail_storage_key', models.CharField(blank=True, max_length=500)),
                ('expected_size_bytes', models.PositiveBigIntegerField()),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_sha256', models.CharField(max_length=64)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING_UPLOAD', 'Pendiente de subida'), ('UPLOADING', 'Subiendo'), ('VERIFYING', 'Verificando'), ('UPLOADED', 'Subido'), ('PROCESSING', 'Procesando'), ('READY', 'Disponible'), ('FAILED', 'Fallido'), ('CORRUPT', 'Corrupto'), ('EXPIRED', 'Expirado'), ('PENDING_DELETE', 'Pendiente de eliminación'), ('DELETED', 'Eliminado')], default='PENDING_UPLOAD', max_length=24)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='events.event')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='operators.operator')),
                ('token_reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='video', to='events.reservedvideotoken')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['operator', 'status'], name='videos_vide_operato_4f5107_idx'), models.Index(fields=['event', 'created_at'], name='videos_vide_event_i_3cbe04_idx'), models.Index(fields=['expires_at'], name='videos_vide_expires_bd6224_idx')],
            },
        ),
    ]
