# Generated by Django 5.2.17 on 2026-09-17 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('offset', models.PositiveBigIntegerField()),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('storage_key', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('expected_size_bytes', models.PositiveBigIntegerField()),
                ('expected_sha256', models.CharField(max_length=64)),
                ('part_size_bytes', models.PositiveIntegerField()),
                ('received_bytes', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('CREATED', 'Creada'), ('RECEIVING', 'Recibiendo'), ('VERIFYING', 'Verificando'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida'), ('ABORTED', 'Abortada'), ('EXPIRED', 'Expirada')], default='CREATED', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_sessions', to='operators.operator')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
