# Generated by Django 5.2.17 on 2026-09-17 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_sessions', to='videos.video'),
        ),
        migrations.AddField(
            model_name='uploadpart',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='uploads.uploadsession'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['status', 'expires_at'], name='uploads_upl_status_818213_idx'),
        ),
        migrations.AddConstraint(
            model_name='uploadsession',
            constraint=models.UniqueConstraint(fields=('operator', 'idempotency_key'), name='unique_upload_idempotency_key_per_operator'),
        ),
        migrations.AddConstraint(
            model_name='uploadsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('CREATED', 'RECEIVING', 'VERIFYING'))), fields=('video',), name='unique_active_upload_per_video'),
        ),
        migrations.AddConstraint(
            model_name='uploadpart',
            constraint=models.UniqueConstraint(fields=('session', 'number'), name='unique_part_number_per_upload'),
        ),
    ]
