# Generated by Django 5.2.17 on 2026-09-17 02:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('max_events_per_month', models.PositiveIntegerField(default=10)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('max_storage_bytes', models.PositiveBigIntegerField(default=53687091200)),
                ('max_devices', models.PositiveIntegerField(default=1)),
                ('branding_enabled', models.BooleanField(default=False)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('price', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('TRIAL', 'Prueba'), ('ACTIVE', 'Activa'), ('PAST_DUE', 'Pago pendiente'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], default='TRIAL', max_length=20)),
                ('provider', models.CharField(choices=[('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_current', models.BooleanField(default=True)),
                ('provider_reference', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='operators.operator')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('operator',), name='unique_current_subscription_per_operator')],
            },
        ),
    ]
